name: Update Result

on:
    workflow_dispatch:
    schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Checkout data
        run: |
          git pull
          git checkout data

      - name: Install httpx
        run: pip install httpx

      - name: Download and unzip file
        run: |
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip Xray-linux-64.zip

      - name: Execute test process
        run: python ./main.py

      - name: Commit and push changes
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

          git add results.txt
          git commit -m "Update content of files"
          git push
